# Generated by Django 5.0.1 on 2024-04-25 18:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='liked_users',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
