# Generated by Django 5.0.1 on 2024-02-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_recent_passwords_resetpasswordtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
