# Generated by Django 5.0.1 on 2024-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appusers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appusers',
            name='verify_pic_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
