# Generated by Django 5.0.1 on 2024-03-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_likes_alter_events_category_and_more'),
        ('users', '0004_appusers_profile_pic_url_appusers_verify_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='user_events',
            field=models.ManyToManyField(blank=True, to='events.events'),
        ),
    ]
