# Generated by Django 5.0.1 on 2024-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appusers_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='cordinates',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
