# Generated by Django 5.0.1 on 2024-03-03 14:01

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appusers_cordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appusers',
            old_name='cordinates',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='connections_no',
        ),
        migrations.AddField(
            model_name='appusers',
            name='following',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
