# Generated by Django 5.0.1 on 2024-03-03 21:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_cordinates_appusers_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='followers',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
