# Generated by Django 5.0.1 on 2024-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appusers_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
