# Generated by Django 5.0.1 on 2024-03-13 23:46

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_appusers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='other_pics',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
