# Generated by Django 5.0.1 on 2024-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_appusers_bio_alter_appusers_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='filled_all_info',
            field=models.BooleanField(default=False),
        ),
    ]
