# Generated by Django 5.0.1 on 2024-05-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_appusers_filled_all_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
