# Generated by Django 5.0.1 on 2024-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_appusers_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
