# Generated by Django 5.0.1 on 2024-03-04 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_appusers_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=500, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('internship', 'Internship'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('apply_link', models.URLField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appusers')),
            ],
        ),
    ]
