# Generated by Django 5.0.1 on 2024-04-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_appusers_other_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_kitchen', 'Home & Kitchen'), ('health_beauty', 'Health & Beauty'), ('toys_games', 'Toys & Games'), ('sports_outdoors', 'Sports & Outdoors'), ('books', 'Books'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('pet_supplies', 'Pet Supplies'), ('tools', 'Tools & Home Imporovement'), ('baby', 'Baby'), ('handmade', 'Handmade'), ('software', 'Software')], max_length=500, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'Brand New'), ('fairly_used', 'Fairly used')], max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appusers')),
            ],
        ),
    ]
