# Generated by Django 5.0.1 on 2024-05-13 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groups_groupchatmessages'),
        ('users', '0014_appusers_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='members_count',
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(to='users.appusers'),
        ),
        migrations.AddField(
            model_name='groups',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_groups', to='users.appusers'),
        ),
    ]
